// <auto-generated />
namespace GVD2247A5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class newrichtextfields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newrichtextfields));
        
        string IMigrationMetadata.Id
        {
            get { return "202404022124580_new rich-text fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
