// <auto-generated />
namespace GVD2247A5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addedvideotypetoedpisode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedvideotypetoedpisode));
        
        string IMigrationMetadata.Id
        {
            get { return "202404031813261_added video type to edpisode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
